# Generated by Django 5.2.7 on 2025-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=12)),
                ('userno', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('isactive', models.BooleanField(default=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('remark', models.TextField(max_length=200)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('createuser', models.CharField(max_length=50)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('updateuser', models.CharField(max_length=50)),
            ],
        ),
    ]
