# Generated by Django 5.2.7 on 2025-10-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysuser',
            name='userid',
        ),
    ]
